### ISSUE TITLE
[feature request] Esc to remove cursors

### ISSUE THREAD

**Issue by flatr0ze** [jonathanpoelen/ktexteditor-multicursors#3]
Hello again, Jonathan.

I was wondering if you could implement the Esc button for removing the cursors someday.

Tried to do that myself last night using the code from https://github.com/azat/kate/blob/master/kate/plugins/gdbplugin/plugin_kategdb.cpp (handleEsc in particular) but couldn't get past the issue of not having mainWindow() to pass as the first argument for connect().

Not urgent, just to make it more interactive.

Thanks!

**Comment by jonathanpoelen** [comment]
Hello.

The plugin is a KTextEditor::Plugin (extension in Kate) and not a Kate::Plugin. There is no access to mainWindow() and I did not find any equivalent.

As a solution, I intercepted every esc, but I can not determine the context. For example, esc on the menu removes the cursors. Idem to stop a selection, because the text is deselect before I receive the event.
